//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "datacap")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub application_onchain_address: Option<String>,
    pub amount: Option<String>,
    pub requested: Option<bool>,
    pub created: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::applications::Entity",
        from = "Column::ApplicationOnchainAddress",
        to = "super::applications::Column::OnchainAddress",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Applications,
}

impl Related<super::applications::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Applications.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
