//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "users")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub onchain_address: String,
    pub github_handle: Option<String>,
    pub user_type: Option<i32>,
    pub created: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::blockchain::Entity")]
    Blockchain,
}

impl Related<super::blockchain::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Blockchain.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
