name: Docker Image CI/CD Test Action

on:
  push:
    branches:
      - workflow-cd-process

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::879175616414:role/GithubActionECRPush
          aws-region: us-east-1
      
      - name: Build and tag Docker image
        run: |
         docker build . -t my-docker-image:latest
    
      - name: Push to ECR
        run: |
         docker push my-docker-image:latest
  