name: Docker Image CI/CD Test Action

on:
  push:
    branches:
      - workflow-cd-process

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
     
    - name: Build and tag Docker image
      run: |
        echo "Building Docker image..."
        docker build . -t public.ecr.aws/b3c4u5n1/filecoin-core-api:latest
        echo "Docker image built and tagged successfully."
        run: echo "build-status=success" >>$GITHUB_OUTPUT

    - name: Push Docker image to ECR
      run: |
        echo "Pushing Docker image to ECR..."
        docker push public.ecr.aws/b3c4u5n1/filecoin-core-api:latest
        echo "Docker image pushed successfully."
        run: echo "push-status=success" >>$GITHUB_OUTPUT
