name: End to End Tests

on:
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  end_to_end_tests:
    name: Perform end-to-end tests
    runs-on: ubuntu-latest
    environment: staging

    steps:
    - uses: actions/checkout@v3
    - name: Run tests
      env: 
        GH_PRIVATE_KEY: "-----BEGIN RSA PRIVATE KEY-----MIIEowIBAAKCAQEA2B4+uEjPfsJYRfhJw3Qfoi9SmKHv6QDOhCeR2d9ydrLVs0PMLaG/ly86rXnmKVzRyvWqDXiUSR4nlZWzU+iOj4u7IPFb6DqHaN2KHbPTc1HpUCyMtuPKy+4N6Zj2Cbd3ynORNMAapmkPxjFY4Fje7qLdrBCVG9+Z7sX66Xl9W5ghbBEkCHeTrzCeCcTEv2kCafrIs1PsUQJ0my+1N8KTWyP2SL5HjIoQqDRCh7q1jLALYbpMp4Z/aLSnjB+vYtTh7LDauzuuwFxYD1lsbpeSDMFJCx7ktguMOKBZs8esASJ/eyDDx2mM3KrsXuwpkWQ6csEcVdAWXLCaUy+kIsG6IwIDAQABAoIBAGDjZlDt64Azlql/v2oNtGTcfFYLO2glQXCD4OJhR4qpcB7XBUFr413fAZpmLOZcQ32PFzbE2Q3SpAJuw5+Zgdge17zUF9UL8Er2DwZz6RcpIMUdw9P2WaOFTN1uAtemVeEAYJfai9gQ/85lryedEAzCHUkXghGl8/fU8EEdgzK9NUFUuZ0Roz0kpCPRH4VVYCwrQ5kRhuJm2q4NVBuzTGuNy/uwzKnBcoWFyckGDdYGGxc2h+cRXW51Cd5kKEujO0lj1CVoTQAO4PUmXDqX5q3W/wwa4ydtIHxCZkEMl+6WRNsSrNZPseveAxW5PK0MtO1HhsysHpZ5n+FuFzA2olkCgYEA8KwehxtmL4xfLnJSaG0Mi/YPSiLDAeRKR8h3RReLS14vQlOK0zqaBiVuwqsn72deFziGf62SFZR6urOlRmGB/rkJFxMYhSEA00O9XeaKe8S0WId7XO9dd97wSRUWjxnUAErgJ9EmPYjNY3Kbea3kdRg68CGjVgT2xyk02Tuz9jcCgYEA5eHMXyJqiEeof81964SMs+tJJ1fyehQTEdAzycQfnYaqLM3xDHR1QxyJrmZmFe5bupczMs9fFW03OuBjsqQ4NWeTZaYhIzlT9t4ADcqOo9QHkIMiTc4VbS+WRQZ+FJJ9ziBWbXpFS2ArOuh+/C2eRFsn/e94/SM6Po15ltJV5XUCgYEAsD3avSWbVwZ8TQ76ue3hWjz+RVPfaes7WgW7EaWEI9T81p1G9Bfd4tJWoceknvQbOvXxyF3atGLe3Qng5gFRqK7nsTYSpqrcZ9kbO0Av+SK6znmoJQ5EbBud6ma+9lv7m5s5Ou82Cam8fi7XG+vzeKwdvOtlKQDJll7ejJXj21ECgYAlxF3+NzpHX3Z4YLtSSTmQiZRAKXvFwKyNXaZUfKsxByHIMKFsiWmGeBbKlzooWjupwROBQn59l67eNmVKwR4W8AhQR+Xj0pRP15MssN2UXs5LWK/3FmeAw7OtbW6jVJnkln18iPz/cDJKAE50gc4hrtQ4LPK0q+fyxO138OB5zQKBgFJQyBLQQBMcBsxlehDxDRFHe2O98YQQU/JNmvOatvfPafRk6zg6XfeRAYq2sBunz6uSOyHX6dPcEHy29r5uq/j0ARqQUBP8L3g5aBTIeAQDu6AuFwgF3maWK4CFcOJBjEtMaBce06l8qZgYxJ8I4oVh7dO8W//jVHbnBLfL9Z/L-----END RSA PRIVATE KEY---—"
        DB_URL: "http://fp-staging-database.cijyyto8juec.us-east-1.rds.amazonaws.com/"
      run: cargo test -- --nocapture
