name: Test linter and code formatter

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    strategy:
      fail-fast: true

    name: Clippy linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Install Clippy
        run: rustup update && rustup component add clippy

      - name: Run Clippy
        run: cargo clippy

  formatting:
    strategy:
      fail-fast: true

    name: cargo fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt

      - name: Rustfmt Check
        uses: actions-rust-lang/rustfmt@v1
