name: Publish new build
run-name: "Publish new images for ${{ github.ref_name }} triggered by ${{ github.actor }}; version: ${{ inputs.version || 'N/A'}}"

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      version:
        description: "Enter the version number"
        required: true
        default: "latest"
      deploy:
        description: "Deploy the new version?"
        required: false
        type: boolean
        default: false
      environment:
        required: false
        description: "Select the environment to deploy to"
        type: choice
        options:
          - staging
          # TODO: uncomment this when we want to deploy to production
          # - production
        default: staging

jobs:
  code-check:
    uses: ./.github/workflows/code-check.yml
    secrets: inherit

  bump-version:
    runs-on: ubuntu-latest
    needs: code-check
    if: ${{ github.ref_name == 'main' && inputs.version != '' }}
    outputs:
      commit_sha: ${{ steps.commit-version.outputs.commit_sha }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install cargo-edit
        run: cargo install cargo-edit

      - name: Update version
        run: cargo set-version ${{ inputs.version }}

      - name: Run cargo check
        run: cargo check

      - name: Git config
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

      - name: Commit version change
        id: commit-version
        run: |
          git commit -am "Update version to ${{ inputs.version }}"
          git push origin main
          echo "commit_sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

  build-and-publish:
    needs:
      - code-check
      - bump-version
    if: |
      always() &&
      !contains(needs.*.result, 'failure') &&
      !contains(needs.*.result, 'cancelled')
    uses: ./.github/workflows/build-docker-image.yml
    with:
      version: ${{ inputs.version }}
      commit_sha: ${{ github.ref_name == 'main' && inputs.version != '' && needs.bump-version.outputs.commit_sha || '' }}
    secrets: inherit

  git-tag:
    runs-on: ubuntu-latest
    needs:
      - bump-version
      - build-and-publish
    if: |
      ${{ github.ref_name == 'main' && inputs.version != '' }} &&
      always() &&
      !contains(needs.*.result, 'failure') &&
      !contains(needs.*.result, 'cancelled')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ needs.bump-version.outputs.commit_sha }}
      - name: Create and push tag
        run: |
          TAG_NAME="v${{ inputs.version }}"
          git tag $TAG_NAME
          git push origin $TAG_NAME

  trigger-deploy:
    needs:
      - code-check
      - bump-version
      - git-tag
    uses: ./.github/workflows/put-ssm-version-deploy.yml
    if: |
      ${{ inputs.version != '' && inputs.deploy == true }} &&
      always() &&
      !contains(needs.*.result, 'failure') &&
      !contains(needs.*.result, 'cancelled')
    with:
      version: ${{ inputs.version }}
      environment: ${{ inputs.environment }}
      ecr-repository: filplus-backend
    secrets: inherit
