name: Release New Version
run-name: New release for "${{ github.ref_name }}" triggered by ${{ github.actor }}

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - workflows

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Install Clippy
        run: rustup update && rustup component add clippy

      - name: Run Clippy
        run: cargo clippy

      - name: Build
        run: cargo build --release

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1
        with:
          mask-password: "true"

      - name: Build and tag Docker image
        env:
          IMAGE_TAG: ${{ github.ref_name }}
          ECR_REPOSITORY: "filplus-backend"
        run: |
          BRANCH_NAME=$(echo $IMAGE_TAG | tr '/' '-')
          echo "Building Docker image $BRANCH_NAME"
          docker build -t "public.ecr.aws/f4h6r4m9/$ECR_REPOSITORY:$BRANCH_NAME" .
