name: Release New Version
run-name: New release for "${{ github.ref_name }}" triggered by ${{ github.actor }}

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - workflows

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Install Clippy
        run: rustup update && rustup component add clippy

      - name: Run Clippy
        run: cargo clippy

      - name: Build
        run: cargo build --release
