name: Release New Version

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - workflows

jobs:
  set-branch-tag-name:
    runs-on: ubuntu-latest
    outputs:
      branch-tag-name: ${{ steps.set-branch-tag-name.outputs.branch-tag-name }}
    steps:
      - name: Extract tag name
        id: set-branch-tag-name
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            BRANCH_TAG=$(echo "${{ github.head_ref }}" | tr '/' '-')
          else
            BRANCH_TAG=$(echo "${{ github.ref_name }}" | tr '/' '-')
          fi
          echo "::set-output name=tag-branch-name::${BRANCH_TAG}"

  build:
    runs-on: ubuntu-latest
    name: New release for "${{ needs.set-branch-tag-name.outputs.branch-tag-name }}" triggered by ${{ github.actor }}
    env:
      BRANCH_TAG: ${{ needs.set-branch-tag-name.outputs.branch-tag-name }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # - name: Install Rust
      #   uses: actions-rust-lang/setup-rust-toolchain@v1

      # - name: Install Clippy
      #   run: rustup update && rustup component add clippy

      # - name: Run Clippy
      #   run: cargo clippy

      # - name: Build
      #   run: cargo build --release

      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v2

      # - name: Configure AWS credentials
      #   uses: aws-actions/configure-aws-credentials@v2
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: eu-central-1

      # - name: Login to Amazon ECR
      #   uses: aws-actions/amazon-ecr-login@v1
      #   with:
      #     mask-password: "true"

      # - name: Build and tag Docker image
      #   env:
      #     ECR_REPOSITORY: "filplus-backend"
      #     IMAGE_TAG: ${{ env.BRANCH_TAG }}
      #   run: |
      #     echo "Building Docker image $IMAGE_TAG"
      #     docker build -t "public.ecr.aws/f4h6r4m9/$ECR_REPOSITORY:$IMAGE_TAG" .
